apiVersion: v1
kind: ServiceAccount
metadata:
  name: xgoods-backend-signup-sa
  namespace: xgoods
  labels:
    name: xgoods
    app: signup
    env: development
    ver: "1.0"
    component: xgoods-backend-signup
