apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: xgoods-storageclass
  labels:
    name: xgoods
    app: signup
    env: development
    ver: "1.0"
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: xfs
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: topology.kubernetes.io/zone
    values:
    - us-east-1a
