apiVersion: v1
kind: Secret
metadata:
  name: xgoods-db-signup-secret
  namespace: xgoods
  labels:
    name: xgoods
    app: signup
    env: development
    ver: "1.0"
    component: xgoods-db-signup
type: Opaque
data:
  # 'root' encoded in base64
  mysql-root-password: cm9vdA==
